.Dd 9/10/22                 \" DATE
.Dt password-generatator    \" Program name and manual section number
.Os j0giwa
.Sh NAME                    \" Section Header - required - don't modify
.Nm password-generator
.Sh SYNOPSIS                \" Section Header - required - don't modify
.Nm
.Op Fl l -v                
.Op length
.Sh DESCRIPTION             \" Section Header - required - don't modify
.Nm 
will print a series of random characters to stdout.
.Pp
A list of flags and their descriptions:
.Pp
.Bl -tag -width -indent     \" Differs from above in tag removed
.It Fl l [length]
Secify the lentgth of the output.
.It Fl v
Print version information and exit.
.El
.Sh BUGS                    \" Document known, unremedied bugs
No known bus at the time
